name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 7.9.5
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile

      - name: VueHooks Plus-Build
        run: |
          cd packages/hooks
          pnpm install
          pnpm run build

      - name: VueHooks Plus-Test
        run: |
          cd packages/hooks
          pnpm run test
        env:
          CI: true
