name: "Node CI"

on: [push, pull_request]

jobs:
  build:
     runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
  steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Install pnpm
     uses: pnpm/action-setup@v2.2.2

    - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
    - name: pnpm run intall, build
      run: |
          cd packages/hooks
          pnpm install
          pnpm build
    - name: pnpm run test
      run: pnpm tets    